main.py

* Backend
- REST-API
* Feature
BITTE Mergen. Danke :)

branch push

---

api/endpoints.py

* Backend
- REST-API
* Feature

35: Call Beispiel Pull Request für alle

---

README.md

README
* Sonstiges: Readme
- [X ] @NimsaJ150 / @JonathanFreydank
Es gibt keinen funktionalen Reviewer. 
Falls jemand Fragen zu der Installation, oder zu Flask allgemein hat, kann derjenige sich gern bei mir melden. Helfe bei Flask gerne.

59: Anleitung "Lokale Installation" zum README hinzugefügt

---

.gitignore
docu/IntelliJ.md
docu/Repository.md

* Dokumentation
* Sonstiges: Projektdokumentation
Es gibt keine funktionale Review. Neben der Repo Dokumentation wurde eine kleine Änderung an dem IntelliJ Guide vorgenommen. Außerdem wurden `Pipfile` und `Pipfile.lock` im `.gitignore` ergänzt, damit mögliche, automatisiert durch Pipenv erstellte Dateien nicht in das Repo gelangen.

45: Doku Projektgrundstruktur

---

processing/typeconversion.py

96: typeconversion with both functions

---

api/endpoints.py
frontend/templates/index.html

* Frontend
* Backend
- REST-API
* Feature
auf der lokalen Maschine funktionierte testen nicht mit angebebener IP & Port (wurde ohne Angabe der IP erfolgreich getestet, wir gehen davon aus, dass es auf dem Server funktioniert)

91: endpoint view

---

core.py

* Backend
- Logik
* Feature
Ich denke, die Klasse "Core" macht an dieser Stelle Sinn. Wenn nicht, lasst es mich wissen.

97 core addition

---

.gitignore
api/template_FE_to_BE.json

* Frontend
* Backend
- REST-API
* Feature
Standpunkt jetzt ist es aus unserer Sicht sinnvoller für die Kommunikation vom Backend zum Frontend die Json dynamisch aus der Datenbank rückgabe zu erzeugen (sieht ja immer gleich aus)

json for FE to BE

---

api/endpoints.py
frontend/static/js/js-handler.js
frontend/templates/index.html

* Frontend
* Feature
Bisher existiert noch das Problem, dass die JSON.stringify()-Methode die Zahlen in einen String umwandelt. Da auch im Backend der Datentyp nicht überprüft wird, kommt dann z.B. bei der Berechnung von 5+2 "52" als Ergebnis raus statt 7. Das werde ich noch fixen, indem ich nicht mehr die stringify()-Methode verwende, aber eine Überprüfung im backend würde auch Sinn machen.

92 javascript handler

---

docu/Coding Richtlinie.md

* Dokumentation
* Dokumenatation
Update im Rahmen der Coding Richtlinie. Hierbei geht es vor allem darum, dass statische Inhalte nicht inline, sondern korrekt in Dateien ausgelagert und am richtigen Ort abgelegt werden.

97: coding richtlinie frontend update

---

docu/IntelliJ.md

* Dokumentation
* Dokumentation
Specs zu Einrückungen für Frontend Technologien wurden hinzugefügt.

97: IntelliJ Richtlinie Frontend code style update

---

database/config.py
database/handler/component_handler.py
requirements.txt

* Backend
* Feature
Datentyp timestamps möglicherweise noch anzupassen, je nach Vorgabe aus Datenbank

164: Connection to database, first node, dummy functions

---

database/create_queries_template.md
database/init_db.cypher

* Database
* Sonstiges Doku/Vorlage und init-Skript
Funktionale Review durch Nicolas und Luca, da diese Cypher kennen.
Bitte schaut euch die Queries an und prüft ob diese Sinnhaft sind.

167: DB Init Skript und Create Query Doku

---

create_metrics.py
database/create_queries_template.md
database/handler/metric_handler.py
database/init_db.cypher
database/metrics.csv

* Backend
* Database
* Feature

168: Metric creation via csv

---

database/handler/component_handler.py
docu/Neomodel.md

157 doku für object mapper

---

docu/JSON_objects_definitions.py

* Docu
* Sonstiges: Definition von json Objekten
Bitte ignoriert alle Files außer **docu/JSON_objects_definitions.py**
Ich habe den Fehler gefunden, warum alle anderen Files auch hier auftauchen, wird bei nächsten Branch nicht mehr passieren.
JSON Objekte sind subject to change, sollten aber erstmal genügen

153 process json

---

database/handler/component_handler.py
database/handler/metric_handler.py
database/metrics.csv
docu/Neomodel.md

* Backend
* Feature
Pull request für Cleanup auf 183 -> keine regulärer PR

183 Cleanup <- 143 feature datenbank operationen für komponenten definieren

---

api/endpoints.py
frontend/static/content/de.json
frontend/static/content/mock-data.json
frontend/static/css/styles.css
frontend/static/js/startseite-js-handler.js
frontend/templates/Startseite.html

* Frontend
* Feature
Pull request für Cleanup auf 183 -> keine regulärer PR

183 Cleanup <- 146 frontend view startseite

---

api/endpoints.py
core.py

* Backend
* Core
* Feature
Pull request für Cleanup auf 183 -> keine regulärer PR

183 Cleanup <- 150 komponente anzeigen endpoint

---

api/endpoints.py
core.py

* Backend
* Core
* Feature
Pull request für Cleanup auf 183 -> keine regulärer PR

183 Cleanup <- 155 component create edit

---

api/endpoints.py
core/__init__.py
core/core.py
database/__init__.py
database/handler/component_handler.py
database/handler/process_handler.py
docu/JSON_objects_definitions.py

* Backend
- REST-API
- Logik
* Feature
Bei Fragen gern melden :) Aufgaben die sich noch ergeben: berechnen des risikos und "dranhängen" an das json object, alle handler

198 vorbereitung sprint 7

---

core/core.py
database/handler/metric_handler.py
docu/JSON_objects_definitions.py

227: New JSON objects structure because of changes in processing module

---

create_metrics.py
database/handler/metric_handler.py
database/metrics.csv
frontend/static/content/mapping_metrics_definition.json

* Backend
* Feature
Zusätzliche Vorschläge wurden auf euren Hinweis hin entfernt. In diesem Branch sind nur noch die Aufgaben und keine eigenen Ideen.
P.S. Das Problem mit dem Speichern hatte nichts mit meinem Code zu tun, sondern weil jemand in der Datenbank doppelte Metriken ergänzt hat.

223: metric_update

---

core/core.py
database/handler/process_handler.py
docu/JSON_objects_definitions.py

200 created operations with process reference

---

frontend/templates/index.html

* Frontend
* Sonstiges: Cleanup
Merge von branches zum Kreieren eines gemeinsamen Frontend Cleanups. Daher keine gemeinsame Review erforderlich.

Cleanup: 212 <- 214

---

frontend/static/content/mapping_metrics_definition.json

* Frontend
* Sonstiges: JSON-file

200: Anpassung V8 eng Excel

---

frontend/templates/index.html

I56_Tabellenbreite angepasst

---

frontend/static/js/component-editor.js
frontend/static/js/helper.js
frontend/templates/component.html
frontend/templates/index.html
frontend/templates/process.html

I54_EorrorHandling added

---

frontend/static/js/process-editor.js

* Frontend
* Feature
Alert für das Löschen einer Componente im ProzessEditor hinzugefügt

I62_deleteCallback added

---

frontend/static/js/component-editor.js
frontend/static/js/process-editor.js

* Frontend
Der Button wird jetzt nur noch bei Erfolgreichem Speichern ausgegraut/disabled. Da nach dem Speichern die Seite neugeladen werden muss ist der Buttton wieder aktiv.

I69_Bug fixed

---

database/handler/process_handler.py
docu/JSON_objects_definitions.py
frontend/static/content/en.json
frontend/static/css/process_styles.css
frontend/static/js/process-editor.js
frontend/templates/process.html

* Frontend
* Backend
* Feature
Beim Programmieren ist uns aufgefallen dass die Label im HTML hargecoded sind: siehe #75 
Außerdem wäre es eine überlegung wert, den namen und die person nebeneinander anzuzeigen

292 ansprechpartner prozesse

---

frontend/static/js/dashboard-renderer.js
frontend/static/js/modals.js
frontend/templates/index.html

* Frontend
* Issue 81
Gerne Rückmeldung, meine erste Frontend-Arbeit.

#81: Cleaned up Link references of Issue #81.

---

frontend/static/content/en.json
frontend/templates/component.html
frontend/templates/index.html
frontend/templates/process.html

* Frontend
* Issue 
https://github.com/Praxisprojekt2021/praxisprojekt/issues/75 
Fix von: "Bezeichnungen im Processview & ComponentView sind hardgecoded auf deutsch und werden nicht über json eingelesen"

I75_Deutsche_Beschreibungen_in_Einzel-Views

---

frontend/static/css/process_styles.css
frontend/static/js/process-editor.js
frontend/templates/process.html

93 rework visualizeprocess

---

frontend/static/content/mapping_metrics_definition.json
frontend/static/css/styles.css
frontend/static/js/component-editor.js
frontend/static/js/helper.js
frontend/static/js/process-editor.js

* Frontend
* Feature
closes #I66
Noch einen Bug gefixt, wo der loading screen nicht weggeht nach nicht erfolgreichem speichern.
Min/Max Überprüfung wurde mit Textalert implementiert und, falls eine Metrik jetzt nicht im Min/Max ist oder nicht ausgefüllt ist wird sie rot markiert, um es dem Nutzer leichter zu machen die falsche Metrik zu finden.
Das mergen dieses Branches führt aber auch dazu, dass die ganzen Komponenten jetzt richtig abgespeichert werden müssen (Die alten Komponenten zum testen müssten gegeben Falls aktualisiert werden)

I66 cleanup

---

frontend/static/css/styles.css
frontend/static/js/component-editor.js
frontend/static/js/dashboard-renderer.js
frontend/static/js/helper.js
frontend/static/js/process-editor.js
frontend/static/js/translator.js
frontend/templates/component.html
frontend/templates/process.html

* Frontend
* Cleanup
Issue #94 Fixed
I66 Branch als Basis genommen
I94 Requests vereinheitlichen
* get_request & post_request -> http_request zusammengefügt
-> http_request(requestType, endpoint, async, post_json, ...callbacks)
* Alle get_request & post_request durch http_request ersetzt
* Alle "manuell" gemachten get und post requests durch http_request ersetzt
* +Inline comments

WIP: I94 requests vereinheitlichen

---

frontend/static/js/component-editor.js
frontend/static/js/process-editor.js
processing/calculations.py

* Frontend
Bitte gut Testen! Hauptsächlich beim Laden und Speichern von Prozessmetriken. Closes #126 
Kommentare und docstrings fehlen noch -> sollten von wem anders nachgezogen werden?

349: Reformatierung, Modularisierung und Quick fixes

---

docu/JSON_objects_definitions.py
frontend/static/js/dashboard-renderer.js
frontend/static/js/helper.js
frontend/static/js/modals.js
frontend/static/js/process-editor.js

* Frontend
* Doku
* Sonstiges CleanUp
-

I51 transfer todos in github issues

---

frontend/static/js/component-editor.js
frontend/static/js/dashboard-renderer.js
frontend/static/js/helper.js
frontend/static/js/info.js
frontend/static/js/modals.js
frontend/static/js/process-editor.js
frontend/static/js/translator.js

* Frontend
* Sonstiges Cleanup

Issue 134 Frontend String Formatierung nachziehen 

---

frontend/static/css/process_styles.css

* Frontend
Button war nur nicht anclickbar
Closing #148

I148: Prozess-Seite wird nicht aktualisiert wenn Komponente aus Prozess gelöscht wird

---

frontend/static/js/dashboard-renderer.js
frontend/static/js/process-editor.js
processing/calculations.py

* Frontend
* Sonstiges: Cleanup
Fix von https://github.com/Praxisprojekt2021/praxisprojekt/issues/131

I131: null als Prozessrisiko Wert von Startseite entfernen

---

database/handler/component_handler.py
database/handler/process_handler.py

* Backend
beim testen über create metrics wird fehler als traceback in die konsole geprinted, in "real life" wird das vom error handler abgefangen
--> wenn fehler innerhalb add component/ add process werden vorherigen steps "gerollbackt"
closes #52

I52_db transaction for add component & process

---

create_metrics.py
database/handler/metric_handler.py
database/handler/queries.py

* Backend
* Database
constraint wurde in unserer neo4j datenbank bereits gesetzt. Zum testen der query bitte lokale instanz benutzen, bzw im db menü die constraint hiermit entfernen: Drop CONSTRAINT ON (n:Metric) ASSERT n.name IS UNIQUE und dann über create metrics hinzufügen

I48 gleiche metrik namen

---

frontend/static/content/en.json
frontend/static/css/Info_styles.css
frontend/templates/info.html

* Frontend
* Design
closes #132

I132 about neues design übernehmen

---

frontend/static/css/styles.css

* Frontend
added overflow:hidden to #processTable .col1 @styles.css

i168: fixed Prozessname in Dashboard-Ansicht

---

frontend/static/js/dashboard-renderer.js
frontend/templates/index.html

382 loading screen startseite

---

frontend/static/js/process-editor.js

I167 missing min / max values

---

database/handler/queries.py

* Database
* Sonstiges, Formatierung

i111_cypherdoku_stringformatierung

---

frontend/static/js/component-editor.js
frontend/static/js/helper.js
frontend/static/js/process-editor.js

* Frontend
* Cleanup
Alle functions modularisiert / cleaned die im Issue #144 erwähnt worden sind soweit sinnvoll
Closes #114

I114 js code cleanup

---

frontend/templates/component.html

* Frontend
Mir ist aufgefallen das in der Webconsole ein Fehler fliegt wenn man /component aufruft --> hat aber nix mit dem PR zutun, ggf. Issue erstellen. Prüfe das morgen nochmal
closes #189

I189: hide uid

---

api/endpoints.py
frontend/static/js/component-editor.js
frontend/static/js/process-editor.js

I47: konsolen ausgaben entfernen

---

frontend/static/js/modals.js

* Frontend
Threshold in Absprache mit Fach-Seite auf einen Monat festgelegt.

I139_update_outdated_threshold

---

frontend/static/js/process-editor.js
requirements.txt
unittesting/test_database_handler/test_process_handler.py

* Frontend
Done:
- Percentage wurde nicht angezeigt bei binären Metriken
- Es waren noch TODOs im Code
- Es waren fehlerhafte disabled commands im Process View
- Die Requirements waren fehlerhaft
Closes #196

I196 hotfixes
